version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    restart: always
    tty: true

  cusmato:
    build: .
    container_name: cusmato
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your_secret_key_here
      - OPEN_WEBUI_PORT=8080
    volumes:
      - cusmato:/app/backend/data
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  ollama:
    driver: local
  cusmato:
    driver: local